import { Logo } from './components/icons/logo'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <body className={inter.className}>
        <header className='py-10'>
          <h1 className='flex flex-col items-center justify-center text-lg'>
            <Logo />
            <strong className='font-semibold tracking-wider text-black/80'>Añadir Experiencia Laboral Automaticamente</strong>
          </h1>
        </header>

        {children}
      </body>
    </html>
  )
}
